jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Build the project using Maven
    - name: Build with Maven
      run: mvn -B clean package --file ecommerce-multivendor-backend-master/pom.xml -DskipTests

    # Deploy artifact to Nexus
    - name: Deploy to Nexus Repository
      run: mvn deploy --settings .github/maven-settings.xml --file ecommerce-multivendor-backend-master/pom.xml
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
