name: Build and Deploy

on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn deploy -X
        working-directory: /home/runner/work/B2C-Project/B2C-Project/ecommerce-multivendor-backend-master

      - name: Print Surefire Test Reports
        if: failure()
        run: cat /home/runner/work/B2C-Project/B2C-Project/ecommerce-multivendor-backend-master/target/surefire-reports/*.txt
        continue-on-error: true

      - name: Upload artifact to Nexus
        if: always()
        env:
          NEXUS_URL: http://13.233.110.84:8081/repository/maven-releases/  # New Nexus URL
          NEXUS_USER: ${{ secrets.NEXUS_USER }}  # Store this secret in your GitHub repository settings
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}  # Store this secret in your GitHub repository settings
        run: |
          mvn deploy:deploy-file \
            -DgroupId=com.example \
            -DartifactId=my-artifact \
            -Dversion=1.0.0 \
            -Dpackaging=jar \
            -Dfile=target/my-artifact-1.0.0.jar \
            -DrepositoryId=nexus \
            -Durl=${{ env.NEXUS_URL }}
        working-directory: /home/runner/work/B2C-Project/B2C-Project/ecommerce-multivendor-backend-master
        continue-on-error: true
