name: Build and Deploy

on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean test -X
        working-directory: /home/runner/work/B2C-Project/B2C-Project/ecommerce-multivendor-backend-master

      - name: Print Surefire Test Reports
        if: failure()
        run: cat /home/runner/work/B2C-Project/B2C-Project/ecommerce-multivendor-backend-master/target/surefire-reports/*.txt
        continue-on-error: true
