jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Build the project using Maven
    - name: Build with Maven
      run: mvn -B clean package --file ecommerce-multivendor-backend-master/pom.xml -DskipTests

 
